language: node_js
node_js:
  - 13

script:
  - git submodule update && cd ./modpack && git checkout $BRANCH && git reset --hard "$COMMITHASH" && cd .. && gulp

before-deploy:
  - mv ./build/server.zip ./build/$ARCHIVENAME.zip

deploy:
  - provider: releases
    token: "$GITHUB_TOKEN"
    file:
      - ./build/$ARCHIVENAME.zip
