language: node_js
node_js:
  - 13

script:
  - bash .travis.sh

before-deploy:
  - mv ./build/server.zip ./build/$ARCHIVENAME.zip

deploy:
  - provider: releases
    overwrite: true
    tag_name: $TAG
    skip_cleanup: true
    token: "$GITHUB_TOKEN"
    file:
      - ./build/$ARCHIVENAME.zip
